language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtest-dev cmake 
compiler:
  - g++
script: cmake CMakeLists.txt && make && ./runTests
notifications:
  email:
    recipients:
      - user1@somewhere.com
      - user2@somewhere.com
    on_success: change
    on_failure: always

