language: cpp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtest-dev cmake 
compiler:
  - g++
script: ./installscr.sh && cmake CMakeLists.txt && make && ./tests
notifications:
  email:
    recipients:
      - erlender@gmail.com
      - user2@somewhere.com
    on_success: change
    on_failure: always

