language: cpp
compiler:
  - g++
script: g++ test.cc helperfunctions.cc && ./a.out
notifications:
  email:
    recipients:
      - user1@somewhere.com
      - user2@somewhere.com
    on_success: change
    on_failure: always

