language: cpp
compiler:
  - g++

#script: make && make test
script: g++ test.cc
notifications:
  email:
    recipients:
      - user1@somewhere.com
      - user2@somewhere.com
    on_success: change
    on_failure: always

